allowBuilds:
  better-sqlite3: false
  esbuild: true
  msgpackr-extract: false
  sharp: false
minimumReleaseAge: 4320
trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1
  - "@vercel/oidc@3.8.9"
  - "@vercel/cli-config@0.3.0"
  - "@vercel/cli-exec@1.0.1"
  - "@rolldown/binding-android-arm-eabi@1.2.12"
  - "@rolldown/binding-android-arm64@1.2.12"
  - "@rolldown/binding-darwin-arm64@1.2.12"
  - "@rolldown/binding-darwin-x64@1.2.12"
  - "@rolldown/binding-freebsd-x64@1.2.12"
  - "@rolldown/binding-linux-arm-gnueabihf@1.2.12"
  - "@rolldown/binding-linux-arm64-gnu@1.2.12"
  - "@rolldown/binding-linux-arm64-musl@1.2.12"
  - "@rolldown/binding-linux-ppc64-gnu@1.2.12"
  - "@rolldown/binding-linux-s390x-gnu@1.2.12"
  - "@rolldown/binding-linux-x64-gnu@1.2.12"
  - "@rolldown/binding-linux-x64-musl@1.2.12"
  - "@rolldown/binding-openharmony-arm64@1.2.12"
  - "@rolldown/binding-win32-arm64-msvc@1.2.12"
  - "@rolldown/binding-win32-x64-msvc@1.2.12"
